apiVersion: v1
kind: ConfigMap
metadata:
  name: psqlbks3
  namespace: default
data:
  PGHOST: 10.0.0.12
  PGPORT: "5432"
  PGUSER: postgres
  PGPASSWORD: XXXXXXXXXXXXXX
  AWS_ACCESS_KEY_ID: AKIAIXXXXXXXXXXXXx
  AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXx
  BUCKET_NAME: postgres_bks

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: psqlbks3
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: psqlbks3
            image: bgrande/psqlbks3:latest
            envFrom:
            - configMapRef:
                name: psqlbks3
          imagePullSecrets:
          - name: regcred
          restartPolicy: OnFailure